// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/character"
	"github.com/mikestefanello/pagoda/ent/outfit"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// OutfitQuery is the builder for querying Outfit entities.
type OutfitQuery struct {
	config
	ctx            *QueryContext
	order          []outfit.OrderOption
	inters         []Interceptor
	predicates     []predicate.Outfit
	withCharacters *CharacterQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OutfitQuery builder.
func (oq *OutfitQuery) Where(ps ...predicate.Outfit) *OutfitQuery {
	oq.predicates = append(oq.predicates, ps...)
	return oq
}

// Limit the number of records to be returned by this query.
func (oq *OutfitQuery) Limit(limit int) *OutfitQuery {
	oq.ctx.Limit = &limit
	return oq
}

// Offset to start from.
func (oq *OutfitQuery) Offset(offset int) *OutfitQuery {
	oq.ctx.Offset = &offset
	return oq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oq *OutfitQuery) Unique(unique bool) *OutfitQuery {
	oq.ctx.Unique = &unique
	return oq
}

// Order specifies how the records should be ordered.
func (oq *OutfitQuery) Order(o ...outfit.OrderOption) *OutfitQuery {
	oq.order = append(oq.order, o...)
	return oq
}

// QueryCharacters chains the current query on the "characters" edge.
func (oq *OutfitQuery) QueryCharacters() *CharacterQuery {
	query := (&CharacterClient{config: oq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(outfit.Table, outfit.FieldID, selector),
			sqlgraph.To(character.Table, character.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, outfit.CharactersTable, outfit.CharactersColumn),
		)
		fromU = sqlgraph.SetNeighbors(oq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Outfit entity from the query.
// Returns a *NotFoundError when no Outfit was found.
func (oq *OutfitQuery) First(ctx context.Context) (*Outfit, error) {
	nodes, err := oq.Limit(1).All(setContextOp(ctx, oq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{outfit.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oq *OutfitQuery) FirstX(ctx context.Context) *Outfit {
	node, err := oq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Outfit ID from the query.
// Returns a *NotFoundError when no Outfit ID was found.
func (oq *OutfitQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = oq.Limit(1).IDs(setContextOp(ctx, oq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{outfit.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oq *OutfitQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := oq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Outfit entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Outfit entity is found.
// Returns a *NotFoundError when no Outfit entities are found.
func (oq *OutfitQuery) Only(ctx context.Context) (*Outfit, error) {
	nodes, err := oq.Limit(2).All(setContextOp(ctx, oq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{outfit.Label}
	default:
		return nil, &NotSingularError{outfit.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oq *OutfitQuery) OnlyX(ctx context.Context) *Outfit {
	node, err := oq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Outfit ID in the query.
// Returns a *NotSingularError when more than one Outfit ID is found.
// Returns a *NotFoundError when no entities are found.
func (oq *OutfitQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = oq.Limit(2).IDs(setContextOp(ctx, oq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{outfit.Label}
	default:
		err = &NotSingularError{outfit.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oq *OutfitQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := oq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Outfits.
func (oq *OutfitQuery) All(ctx context.Context) ([]*Outfit, error) {
	ctx = setContextOp(ctx, oq.ctx, "All")
	if err := oq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Outfit, *OutfitQuery]()
	return withInterceptors[[]*Outfit](ctx, oq, qr, oq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oq *OutfitQuery) AllX(ctx context.Context) []*Outfit {
	nodes, err := oq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Outfit IDs.
func (oq *OutfitQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if oq.ctx.Unique == nil && oq.path != nil {
		oq.Unique(true)
	}
	ctx = setContextOp(ctx, oq.ctx, "IDs")
	if err = oq.Select(outfit.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oq *OutfitQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := oq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oq *OutfitQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oq.ctx, "Count")
	if err := oq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oq, querierCount[*OutfitQuery](), oq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oq *OutfitQuery) CountX(ctx context.Context) int {
	count, err := oq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oq *OutfitQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oq.ctx, "Exist")
	switch _, err := oq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oq *OutfitQuery) ExistX(ctx context.Context) bool {
	exist, err := oq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OutfitQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oq *OutfitQuery) Clone() *OutfitQuery {
	if oq == nil {
		return nil
	}
	return &OutfitQuery{
		config:         oq.config,
		ctx:            oq.ctx.Clone(),
		order:          append([]outfit.OrderOption{}, oq.order...),
		inters:         append([]Interceptor{}, oq.inters...),
		predicates:     append([]predicate.Outfit{}, oq.predicates...),
		withCharacters: oq.withCharacters.Clone(),
		// clone intermediate query.
		sql:  oq.sql.Clone(),
		path: oq.path,
	}
}

// WithCharacters tells the query-builder to eager-load the nodes that are connected to
// the "characters" edge. The optional arguments are used to configure the query builder of the edge.
func (oq *OutfitQuery) WithCharacters(opts ...func(*CharacterQuery)) *OutfitQuery {
	query := (&CharacterClient{config: oq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oq.withCharacters = query
	return oq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Outfit.Query().
//		GroupBy(outfit.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oq *OutfitQuery) GroupBy(field string, fields ...string) *OutfitGroupBy {
	oq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OutfitGroupBy{build: oq}
	grbuild.flds = &oq.ctx.Fields
	grbuild.label = outfit.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Outfit.Query().
//		Select(outfit.FieldName).
//		Scan(ctx, &v)
func (oq *OutfitQuery) Select(fields ...string) *OutfitSelect {
	oq.ctx.Fields = append(oq.ctx.Fields, fields...)
	sbuild := &OutfitSelect{OutfitQuery: oq}
	sbuild.label = outfit.Label
	sbuild.flds, sbuild.scan = &oq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OutfitSelect configured with the given aggregations.
func (oq *OutfitQuery) Aggregate(fns ...AggregateFunc) *OutfitSelect {
	return oq.Select().Aggregate(fns...)
}

func (oq *OutfitQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oq); err != nil {
				return err
			}
		}
	}
	for _, f := range oq.ctx.Fields {
		if !outfit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oq.path != nil {
		prev, err := oq.path(ctx)
		if err != nil {
			return err
		}
		oq.sql = prev
	}
	return nil
}

func (oq *OutfitQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Outfit, error) {
	var (
		nodes       = []*Outfit{}
		_spec       = oq.querySpec()
		loadedTypes = [1]bool{
			oq.withCharacters != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Outfit).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Outfit{config: oq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oq.withCharacters; query != nil {
		if err := oq.loadCharacters(ctx, query, nodes,
			func(n *Outfit) { n.Edges.Characters = []*Character{} },
			func(n *Outfit, e *Character) { n.Edges.Characters = append(n.Edges.Characters, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oq *OutfitQuery) loadCharacters(ctx context.Context, query *CharacterQuery, nodes []*Outfit, init func(*Outfit), assign func(*Outfit, *Character)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Outfit)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Character(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(outfit.CharactersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.outfit_characters
		if fk == nil {
			return fmt.Errorf(`foreign-key "outfit_characters" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "outfit_characters" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (oq *OutfitQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oq.querySpec()
	_spec.Node.Columns = oq.ctx.Fields
	if len(oq.ctx.Fields) > 0 {
		_spec.Unique = oq.ctx.Unique != nil && *oq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oq.driver, _spec)
}

func (oq *OutfitQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(outfit.Table, outfit.Columns, sqlgraph.NewFieldSpec(outfit.FieldID, field.TypeUint64))
	_spec.From = oq.sql
	if unique := oq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oq.path != nil {
		_spec.Unique = true
	}
	if fields := oq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outfit.FieldID)
		for i := range fields {
			if fields[i] != outfit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oq *OutfitQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oq.driver.Dialect())
	t1 := builder.Table(outfit.Table)
	columns := oq.ctx.Fields
	if len(columns) == 0 {
		columns = outfit.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oq.sql != nil {
		selector = oq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oq.ctx.Unique != nil && *oq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oq.predicates {
		p(selector)
	}
	for _, p := range oq.order {
		p(selector)
	}
	if offset := oq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OutfitGroupBy is the group-by builder for Outfit entities.
type OutfitGroupBy struct {
	selector
	build *OutfitQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ogb *OutfitGroupBy) Aggregate(fns ...AggregateFunc) *OutfitGroupBy {
	ogb.fns = append(ogb.fns, fns...)
	return ogb
}

// Scan applies the selector query and scans the result into the given value.
func (ogb *OutfitGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ogb.build.ctx, "GroupBy")
	if err := ogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OutfitQuery, *OutfitGroupBy](ctx, ogb.build, ogb, ogb.build.inters, v)
}

func (ogb *OutfitGroupBy) sqlScan(ctx context.Context, root *OutfitQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ogb.fns))
	for _, fn := range ogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ogb.flds)+len(ogb.fns))
		for _, f := range *ogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OutfitSelect is the builder for selecting fields of Outfit entities.
type OutfitSelect struct {
	*OutfitQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (os *OutfitSelect) Aggregate(fns ...AggregateFunc) *OutfitSelect {
	os.fns = append(os.fns, fns...)
	return os
}

// Scan applies the selector query and scans the result into the given value.
func (os *OutfitSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, os.ctx, "Select")
	if err := os.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OutfitQuery, *OutfitSelect](ctx, os.OutfitQuery, os, os.inters, v)
}

func (os *OutfitSelect) sqlScan(ctx context.Context, root *OutfitQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(os.fns))
	for _, fn := range os.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*os.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := os.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
