// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Character is the predicate function for character builders.
type Character func(*sql.Selector)

// Outfit is the predicate function for outfit builders.
type Outfit func(*sql.Selector)

// Ribbon is the predicate function for ribbon builders.
type Ribbon func(*sql.Selector)
